# Generated by Django 6.0.2 on 2026-03-14 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_solicitudbaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('delta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('CREACION', 'Creacion'), ('VENTA', 'Venta'), ('BAJA', 'Baja'), ('AJUSTE', 'Ajuste'), ('OTRO', 'Otro')], default='AJUSTE', max_length=12)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('nota', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='products.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
