# Generated by Django 6.0.2 on 2026-03-17 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_movimientostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='products.producto')),
            ],
            options={
                'ordering': ['-activa', '-fecha_inicio'],
            },
        ),
    ]
