# Generated by Django 6.0.2 on 2026-03-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_incluidos', to='products.promocion')),
            ],
        ),
    ]
