# Generated by Django 6.0.2 on 2026-05-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_promocionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo'), ('2X1', '2x1 (Lleva 2, paga 1)')], default='PORCENTAJE', max_length=20),
        ),
    ]
