# Generated by Django 5.2.11 on 2026-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='Consumidor Final', max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_transferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
    ]
