# Generated by Django 5.2.11 on 2026-02-20 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_venta_banco_origen_venta_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='hora_apertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together={('responsable', 'fecha')},
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ventas_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_teorico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_fisico_ingresado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_productos_vendidos', models.PositiveIntegerField(default=0)),
                ('total_transferencias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cerrado', models.BooleanField(default=True)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cierre', to='sales.caja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
