# Generated by Django 6.0.2 on 2026-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_caja_hora_apertura_alter_caja_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10),
        ),
    ]
