# Generated by Codex on 2026-03-11

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_caja_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(
                fields=('responsable',),
                condition=Q(abierta=True, estado='Abierta'),
                name='uniq_caja_abierta_por_responsable',
            ),
        ),
    ]

