# Generated by Codex on 2026-03-11

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_caja_open_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='caja',
            name='uniq_caja_abierta_por_responsable',
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(
                fields=('abierta',),
                condition=Q(abierta=True),
                name='uniq_caja_abierta_global',
            ),
        ),
    ]

