# Generated by Django 6.0.2 on 2026-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_venta_metodo_pago_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='diferencia_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monto_teorico_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='es_promocion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='promocion_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
