# Generated by Django 6.0.2 on 2026-03-25 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_credito_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('VENTA_DETALLE', 'Detalle Venta'), ('CAJA_APERTURA', 'Apertura Caja'), ('CAJA_CIERRE', 'Cierre Caja'), ('GASTO', 'Gasto'), ('CREDITO', 'Crédito'), ('PAGO_CREDITO', 'Pago Crédito'), ('STOCK_ENTRADA', 'Entrada Stock'), ('STOCK_SALIDA', 'Salida Stock'), ('BAJA_STOCK', 'Baja Stock'), ('PRODUCTO', 'Producto'), ('PROMOCION', 'Promoción'), ('USUARIO', 'Usuario'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('APERTURAR', 'Aperturar'), ('CERRAR', 'Cerrar'), ('REGISTRAR', 'Registrar'), ('PAGAR', 'Pagar'), ('ANULAR', 'Anular')], max_length=15)),
                ('descripcion', models.TextField()),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo', '-fecha'], name='sales_movim_tipo_aaf949_idx'), models.Index(fields=['usuario', '-fecha'], name='sales_movim_usuario_f5db2d_idx')],
            },
        ),
    ]
