# Generated by Django 6.0.2 on 2026-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_pagos_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
