# Generated by Django 6.0.2 on 2026-03-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfil_tipo_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
